### PR TITLE
WIP: switch to the flat structure

### PR DESCRIPTION
**Pull request by samm-git**
Hi, sorry for making it as PR again. I tried to follow recommendations in the https://github.com/jralls/gtk-osx-docbook/pull/2 but found that i am not aware how to updated all related xml-s and i am sure that just putting this dirs are not enough, catalogs needs to be regeneratated and i found no evidence how they been generated initially.

So proposing new structure again - i think it is much easy to maintain and update, as it does not depend on any local modifications and adding or removing new catalog is easier. See https://github.com/samm-git/gtk-osx-docbook/tree/flat. However, if you think that its wrong approach - please explain how to update original bundle (and all the files) correctly.

### CODE REVIEW

**Comment by jralls** [comment]
Closing the PR and making a new one with the same unacceptable changes doesn't change anything.

Some more detail: 
The existing package contains DTDs and stylesheets  that were at one time required by something. I didn't build this, Richard Hult did, so I don't actually know what those requirements were and whether they're still needed.  Each one of those drops needs a separate commit explaining what it was needed for in 2009 and why it's not needed now.

Use the currently maintained sources, [docbook/xslt10-stylesheets](https://github.com/docbook/xslt10-stylesheets) and [docbook/docbook](https://github.com/docbook/docbook)instead of the obsolete and unmaintained Sourceforge ones.  The new repos have only one copy of the stylesheets instead of two and support Docbook-5.0.

The existing gtk-osx-docbook uses selected directories that if copied from current source would be 5.6M. You need to justify the extra weight, one commit for each directory.  Frankly I think that it would make more sense to *remove* stylesheet directories, for gtk-osx's purposes it's likely that only html, htmlhelp, and whatever is needed to support those two is really necessary.

IIRC Richard hand-wrote the catalogs. That's why there's no tool to do it. You could write such a tool, but frankly I suspect it would be wasted effort. This package doesn't need to be updated that frequently.

**Comment by samm-git** [comment]
@jralls 
> Closing the PR and making a new one with the same unacceptable changes doesn't change anything.

It was not intentional. I rebased my fork to master and dropped my only commit and GH automatically closed it :)

**Comment by samm-git** [comment]
@jralls As it is build dependency and does not go to the packages source - i don't feel that optimizing space here is worst efforts and this is why i proposed this new structure which is very close to original tarballs. I think if it breaks anything we can easily add missing part and it is much more maintainable compared to original archive. I think here its better to include more and not update tarball every time we found that something is missing.

**Comment by jralls** [comment]
Wrong answer. 
Your version of gtk-osx-docbook is pointless and obsolete. You're wasting your time and mine.

**Pull request closed without merging**
